apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: premium-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "gemma-4-31B-it"
spec:
  priority: 100
  poolRef:
    name: flow-control
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: standard-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "gemma-4-31B-it"
spec:
  priority: 0
  poolRef:
    name: flow-control
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: best-effort-traffic
  labels:
    llm-d.ai/guide: "flow-control"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/model: "gemma-4-31B-it"
spec:
  priority: -10
  poolRef:
    name: flow-control
